<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DAL\MoneyStat.DAL.DataBase\MoneyStat.DAL.DataBase.csproj" />
      <ProjectReference Include="..\..\Infra\MoneyStat.Infra.Helpers\MoneyStat.Infra.Helpers.csproj" />
    </ItemGroup>

</Project>
